# Generated by Django 4.2.4 on 2023-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='emp_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='emp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emp',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='emp',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='emp_set_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
