# Generated by Django 4.2.4 on 2023-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0002_emp_groups_emp_is_active_emp_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='emp',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
