# Generated by Django 4.2.4 on 2023-09-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
