# Generated by Django 4.2.4 on 2023-09-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0006_alter_employee_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmpAdmin',
        ),
    ]
