# Generated by Django 4.2.4 on 2023-09-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0007_rename_employee_empadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
