# Generated by Django 4.2.4 on 2023-10-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0008_emp_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
    ]
