# Generated by Django 4.2.4 on 2023-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0009_remove_task_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
