# Generated by Django 4.2.4 on 2023-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0010_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee_id',
            field=models.CharField(max_length=10),
        ),
    ]
