# Generated by Django 4.2.4 on 2023-10-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empsys', '0012_assigntask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
